name: yalda_students_notes
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-178.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: # Add this line
    sdk: flutter 

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  iconsax: ^0.0.8
  google_fonts: ^2.2.0
  provider: ^6.0.2
  theme_provider: ^0.5.0
  flutter_bloc: ^8.0.1
  intl: ^0.17.0

  drift: ^1.4.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0
  # moor: ^4.3.2
  # moor_db_viewer: ^5.0.0
  # sqlite3: ^1.7.0

  day_night_switcher: ^0.2.0+1
  shared_preferences: ^2.0.12
  equatable: ^2.0.3
  easy_localization: ^3.0.0
  toggle_switch: ^1.4.0
  expandable: ^5.0.1
  modal_bottom_sheet: ^2.0.1
  contained_tab_bar_view: ^0.8.0
  flutter_feather_icons: ^2.0.0+1
  url_launcher: ^6.0.20
  introduction_screen: ^3.0.2
  dropdown_button2: ^1.4.0
  flag: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: 4.1.6
  drift_dev: ^1.4.0
  build_runner: ^2.1.10
  flutter_launcher_icons: "^0.9.2"
  build_web_compilers: ^3.2.1


  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "asset/icon/icon.png"
  image_path_android: "asset/icon/icon.png"

flutter:

  uses-material-design: true
  generate: true

  assets:
    - asset/image/
    - asset/icon/
    - asset/translation/

  fonts:
    - family: ic_font
      fonts:
          - asset: asset/fonts/ic_font.ttf